# Numpy: Matrizes, Vetores e Operações Matemáticas


In [2]:
#Instalação
##pip install numpy

In [3]:
#Import
import numpy as np

In [4]:
#Array 1 (Vetor 1)
v1 = np.array([12, 5, 9])
type(v1)
print(v1)

[12  5  9]


In [5]:
#Array 2 (Vetor 2)
v2 = np.array([[8,2], 
               [10, 3]])
type(v2)
print(v2)

[[ 8  2]
 [10  3]]


In [6]:
#Array 3 (Vetor 3)
v3 = np.array([[[1,5], 
                [4,5]], 
                
                [[6,2],
                 [10,1]]])
type(v3)
print(v3)

[[[ 1  5]
  [ 4  5]]

 [[ 6  2]
  [10  1]]]


In [7]:
print(v1.shape)
print(v2.shape)
print(v3.shape)

(3,)
(2, 2)
(2, 2, 2)


In [8]:
print(np.sum(v1))
print(np.sum(v2))
print(np.sum(v2, axis=0))
print(np.sum(v2, axis=1))

26
23
[18  5]
[10 13]


In [9]:
a = np.array([[1, 2, 3]])
b = np.array([[1],
              [2], 
              [3]])

In [10]:
print(a)
print(a.shape)

[[1 2 3]]
(1, 3)


In [11]:
print(b)
print(b.shape)

[[1]
 [2]
 [3]]
(3, 1)


# Indexação de Arrays

In [12]:

arr = np.array([2, 9, 10, 1, 6, 5])
print(arr[0])
print(arr[-1])
print(arr[1:5])
print(arr[2:])

2
5
[ 9 10  1  6]
[10  1  6  5]


In [13]:
arr2 = np.array([[1, 5, 3], 
                 [3, 5, 9], 
                 [1, 9, 9]])
print(arr2)
print(arr2.shape)

[[1 5 3]
 [3 5 9]
 [1 9 9]]
(3, 3)


In [14]:
print(arr2[0])
print(arr2[0, 2])
print(arr2[0, -2:])
print(arr2[:, 0])

[1 5 3]
3
[5 3]
[1 3 1]


# filtragem de Arrays

In [15]:

print(arr)
print(arr > 5)
print(arr[arr > 5])

[ 2  9 10  1  6  5]
[False  True  True False  True False]
[ 9 10  6]


# Criação de Arrays

In [16]:

# 1. Ones
print(np.ones(5))
print("-" * 15)
print(np.ones((3, 2)))


[1. 1. 1. 1. 1.]
---------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
# 2. Zeros
print(np.zeros(10))
print("-" * 15)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
---------------


In [18]:
# 3. Arange
x = np.arange(0, 123, 10)
print(x)

[  0  10  20  30  40  50  60  70  80  90 100 110 120]


In [19]:
# 4. Linspace
x = np.linspace(0, 123, 10)
print(x)

[  0.          13.66666667  27.33333333  41.          54.66666667
  68.33333333  82.          95.66666667 109.33333333 123.        ]


# Operações com Arrays

In [20]:

a = np.array([5, 9, 1])
b = np.array([1, 7, 8])
soma = a + b
sub = a - b
mult = a * b
divi = a / b
pot = a ** b
print(soma)
print("-" * 30)
print(sub)
print("-" * 30)
print(mult)
print("-" * 30)
print(divi)
print("-" * 30)
print(pot)

[ 6 16  9]
------------------------------
[ 4  2 -7]
------------------------------
[ 5 63  8]
------------------------------
[5.         1.28571429 0.125     ]
------------------------------
[      5 4782969       1]


In [21]:
seno = np.sin(a)
raiz = np.sqrt(a)
print(seno)
print("-" * 60)
print(raiz)

[-0.95892427  0.41211849  0.84147098]
------------------------------------------------------------
[2.23606798 3.         1.        ]


# Operação com Matrizes

In [22]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[10, 9], [8, 7]])
print(m1)
print("-" * 60)
print(m2)

[[1 2]
 [3 4]]
------------------------------------------------------------
[[10  9]
 [ 8  7]]


In [23]:
soma = m1 + m2
sub = m1 - m2
mult = m1 * m2
divi = m1 / m2
pot = m1 ** m2
print(soma)
print("-" * 60)
print(sub)
print("-" * 60)
print(mult)
print("-" * 60)
print(divi)
print("-" * 60)
print(pot)


[[11 11]
 [11 11]]
------------------------------------------------------------
[[-9 -7]
 [-5 -3]]
------------------------------------------------------------
[[10 18]
 [24 28]]
------------------------------------------------------------
[[0.1        0.22222222]
 [0.375      0.57142857]]
------------------------------------------------------------
[[    1   512]
 [ 6561 16384]]


# Operações Estatísticas

In [24]:
print(arr)
print("-" * 60)
print(np.sum(arr))
print("-" * 60)
print(np.min(arr))
print("-" * 60)
print(np.max(arr))
print("-" * 60)
print(np.mean(arr))
print("-" * 60)
print(np.median(arr))

[ 2  9 10  1  6  5]
------------------------------------------------------------
33
------------------------------------------------------------
1
------------------------------------------------------------
10
------------------------------------------------------------
5.5
------------------------------------------------------------
5.5


# Operações Lógicas

In [25]:
estoque = np.array([10, 20, 5]) #Quantidade em estoque
disponibilidade = np.array([1, 10, 2]) #Dias que demora para entregar 

print(np.where(estoque > 5, "OK", "NOT OK")) #Supondo que o min de estoque é 6
print("-" * 60)
print(np.where(disponibilidade <= 3, "OK", "NOT OK")) #e que a disponibilidade é menor q 3
print("-" * 60)
print(np.where((estoque > 5) & (disponibilidade <= 3), "OK", "NOT OK"))#Unindo as duas logicas
print("-" * 60)
print(np.where((estoque > 5) | (disponibilidade <= 3), "OK", "NOT OK"))#Unindo as duas logicas, porem apenas 1 deve ser verdadeiro ou no caso 'OK'

['OK' 'OK' 'NOT OK']
------------------------------------------------------------
['OK' 'NOT OK' 'OK']
------------------------------------------------------------
['OK' 'NOT OK' 'NOT OK']
------------------------------------------------------------
['OK' 'OK' 'OK']


In [26]:
#Exemplo
notas = np.array([45, 75, 60, 90, 50, 80, 30, 65])
print(np.where(notas >= 50, "Aprovada", "Reprovada"))

['Reprovada' 'Aprovada' 'Aprovada' 'Aprovada' 'Aprovada' 'Aprovada'
 'Reprovada' 'Aprovada']


In [27]:
# maior que 90 = A
# maior que 80 = B
# maior ou igual a 50 = C
# menor que 50 = Reprovado
np.select(
    [
        notas > 90,
        notas > 80,
        notas >= 50,
        notas < 50
    ],
    [
        "A",
        "B",
        "C",
        "Reprovado"
    ], default = "Erro"
)

array(['Reprovado', 'C', 'C', 'B', 'C', 'C', 'Reprovado', 'C'],
      dtype='<U9')

# Álgebra Linear

In [28]:
#2x + y = 8
#3x + 4y = 18
A = np.array([[2, 1], [3, 4]])
B = np.array([8, 18])

np.linalg.solve(A, B)

array([2.8, 2.4])

In [29]:
#Determinnante
np.linalg.det(A)

np.float64(5.000000000000001)

In [30]:
#Matriz Inversa
np.linalg.inv(A)

array([[ 0.8, -0.2],
       [-0.6,  0.4]])

In [31]:
#50x + 20y = 4000
#30x + 40y = 3600
C = np.array([[50, 20], [30, 40]])
D = np.array([4000, 3600])

np.linalg.solve(C, D)

array([62.85714286, 42.85714286])